### ISSUE TITLE
备注有误，util包的util.go文件中

### ISSUE THREAD

**Issue by igoodful** [chaosblade-io/chaosblade-spec-go#23]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
/ GetProgramPath
func GetProgramPath() string {
	if proPath != "" {
		return proPath
	}
	dir, err := exec.LookPath(os.Args[0])
	if err != nil {
		log.Fatal("can get the process path")    // 这里应该是 can't get the process path
	}
	if p, err := os.Readlink(dir); err == nil {
		dir = p
	}
	proPath, err = filepath.Abs(filepath.Dir(dir))
	if err != nil {
		log.Fatal("can get the full process path")  // 这里应该是can't get the full process path
	}
	return proPath
}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
It has been fixed. Thank you~
