### ISSUE TITLE
GetPidsByProcessName执行慢，导致burncpu故障执行报signal kill

### ISSUE THREAD

**Issue by selone** [chaosblade-io/chaosblade-spec-go#39]
在channel/local.go的第100行。
函数GetPidsByProcessName在节点进程数量大的情况下非常慢。实测2000个进程的情况下，这个函数要运行20s左右。

gopsutil这个库的Process函数，会大量调用系统的read函数，尤其是进程数量大时。

exec-os库中的burncpu使用了（exec/bin/burncpu/burncpu.go第215行）getPid这个函数。导致cpu故障启动超过60s，会得到一个signal killed。

建议：
1. 更改获得pid的实现方式
或者
2. 在批量启动cpu故障时，先批量创建进程，再总体获取一次pid，进行taskset操作，这样可以缓解一部分问题

感谢！

**Comment by Icesource** [comment]
目前新的发行版已经更改了启动cpu故障的方式，不再需要对每个核执行GetPidsByProcessName函数，请尝试使用新的代码解决该问题
